# Generated by Django 4.2.20 on 2025-04-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='agents_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField()),
                ('responsibilities', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('religion', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('marital_status', models.CharField(max_length=20)),
                ('no_of_children', models.PositiveIntegerField(default=0)),
                ('tribe', models.CharField(max_length=100)),
                ('clan', models.CharField(max_length=100)),
                ('nin_number', models.CharField(max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('working_experience', models.TextField(blank=True)),
                ('country_worked', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_origin_village', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_origin_parish', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_origin_subcounty', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_origin_county', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_origin_district', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address_village', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address_parish', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address_subcounty', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address_county', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address_district', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_dob', models.DateField(blank=True, null=True)),
                ('father_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('father_nin', models.CharField(blank=True, max_length=20, null=True)),
                ('father_district', models.CharField(blank=True, max_length=100, null=True)),
                ('father_tribe', models.CharField(blank=True, max_length=100, null=True)),
                ('father_status', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_dob', models.DateField(blank=True, null=True)),
                ('mother_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_nin', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_district', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_tribe', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_status', models.CharField(blank=True, max_length=20, null=True)),
                ('next_of_kin_name', models.CharField(max_length=100)),
                ('next_of_kin_relationship', models.CharField(max_length=100)),
                ('next_of_kin_contact', models.CharField(max_length=20)),
                ('next_of_kin_address', models.CharField(max_length=200)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('year_start', models.CharField(blank=True, max_length=20, null=True)),
                ('year_end', models.CharField(blank=True, max_length=20, null=True)),
                ('award', models.CharField(blank=True, max_length=200, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('job_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobs')),
                ('job_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.countries')),
                ('referral_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.agents')),
            ],
        ),
    ]
