# Generated by Django 4.2.20 on 2025-04-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='award',
            new_name='education_level',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='school',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='year_start',
        ),
    ]
