# Generated by Django 4.2.20 on 2025-04-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_award_candidates_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='job_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.jobs'),
        ),
    ]
