# Generated by Django 4.2.20 on 2025-04-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_candidates_job_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='job_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.countries'),
        ),
    ]
