# Generated by Django 5.2.3 on 2025-07-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_candidates_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='responsibilities',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
