# Generated by Django 5.2.7 on 2025-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_jobs_description_alter_jobs_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='candidate_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Travelled', 'Travelled')], default='Pending', max_length=20),
        ),
    ]
