# Generated by Django 5.2.7 on 2025-11-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_candidates_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='full_photo',
            field=models.ImageField(blank=True, null=True, upload_to='full_photos/'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='interpol',
            field=models.ImageField(blank=True, null=True, upload_to='interpol/'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='medical_copy',
            field=models.ImageField(blank=True, null=True, upload_to='medical_copies/'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='passport_copy',
            field=models.ImageField(blank=True, null=True, upload_to='passport_copies/'),
        ),
    ]
